[package]
name = "lease_cache_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abstract_cache = {git = "https://github.com/Roc-Locality/abstract_cache"}
rand = "0.8.4"
